# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 064af8307e0cb709eb57d9d56a1d92cdcb374f007102e945a787dc05b50111c1d90e1c7682919b715aa4f7515d9b9584b12709df615a1c60f82b421ffa6acc51

test:
  secret_key_base: ab0be44a61791b909613380a43f466fe5130d2620538bfd1d4ceb04bcf2a6364c5d2276358fb8a2dac483c618a040d1663eed04febb62b2532b90518829048ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
